.PHONY: clean All

All:
	@echo "----------Building project:[ CarpetCleaningService - Debug ]----------"
	@cd "CarpetCleaningService" && "$(MAKE)" -f  "CarpetCleaningService.mk"
clean:
	@echo "----------Cleaning project:[ CarpetCleaningService - Debug ]----------"
	@cd "CarpetCleaningService" && "$(MAKE)" -f  "CarpetCleaningService.mk" clean
