.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengePart7 - Debug ]----------"
	@cd "ChallengePart7" && "$(MAKE)" -f  "ChallengePart7.mk"
clean:
	@echo "----------Cleaning project:[ ChallengePart7 - Debug ]----------"
	@cd "ChallengePart7" && "$(MAKE)" -f  "ChallengePart7.mk" clean
