.PHONY: clean All

All:
	@echo "----------Building project:[ CinCout - Debug ]----------"
	@cd "CinCout" && "$(MAKE)" -f  "CinCout.mk"
clean:
	@echo "----------Cleaning project:[ CinCout - Debug ]----------"
	@cd "CinCout" && "$(MAKE)" -f  "CinCout.mk" clean
